pipeline {
    agent  {
        label 'Agent1'
    }
    environment { 
        appVersion = ''
        REGION = "us-east-1"
        ACC_ID = "315069654700"
        PROJECT = "roboshop"
    }
    options {
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
   
    stages {
        stage('init') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 10-sg
                            terraform init -reconfigure
                        """
                    }
                }
            }
        }

        stage('plan') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 10-sg
                            terraform plan
                        """
                    }
                }
            }
        }
        stage('apply') {
           
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 10-sg
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
        stage('Triggering BASTION EKS ACM ALB') {
           parallel {
                stage('Triggering BASTION'){
                    steps {
                        script {
                        build job: '20-bastion', 
                        propagate: false, //up stream job will not fail even sg fails
                        wait: false // vpc will not wait
                        }
                    }
                }
                 stage('Triggering EKS') {
                    steps {
                        script {
                        build job: '80-eks', 
                        propagate: false, //up stream job will not fail even sg fails
                        wait: false // vpc will not wait
                        }
                    }
                 }   
                stage('ACM ALB') {
                    //sequential
                        stages {
                           stage('Triggering ACM') {
                                steps {
                                    script {
                                    build job: '60-acm', 
                                    propagate: false, //up stream job will not fail even sg fails
                                    wait: false // vpc will not wait
                                    }
                                }
                           }
                            stage('Triggering ALB') {
                                steps {
                                    script {
                                    build job: '70-frontend-alb', 
                                    propagate: false, //up stream job will not fail even sg fails
                                    wait: false // vpc will not wait
                                    }
                                }
                            }       
                        } 
                }
            }
        }
    }
    
    
    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        success { 
            echo 'Hello Success'
        }
        failure { 
            echo 'Hello Failure'
        }
    }
}
